### PR TITLE
Support Input and Output devices

### PR DESCRIPTION
**Pull request by glentakahashi**
Fixes https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/95

### CODE REVIEW

**Comment by SamDel** [comment]
Thanks, works very nice! I'll merge it later (and make a new release).

Just wondering: what do you want to use it for?

**Comment by glentakahashi** [comment]
@SamDel I'd like to be easily able to live broadcast my voice to another room! Much better/easier to use than the built-in broadcast feature :)

Great app btw!

**Comment by SamDel** [comment]
Thanks! 
Maybe new features can be added. Like a microphone button on the main tab as a quick way to send individual messages to another room.

**Comment by hibikijoji** [comment]
Thanks all!

**Pull request merged**
